package com.example.naokihonda.calculator;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;

/**
 * Created by naokihonda on 2017/09/25.
 */

public class User extends RealmObject {
    @Ignore
    private int id;

    public int sum_price;
    public int persons;
    public int result;

    // Standard getters & setters generated by your IDE…

    public int getId() {
        return id;
    }

    public int getSum_price() {
        return sum_price;
    }

    public int getPersons() {
        return persons;
    }

    public int getResult() {
        return result;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setSum_price(int sum_price) {
        this.sum_price = sum_price;
    }

    public void setPersons(int persons) {
        this.persons = persons;
    }

    public void setResult(int result) {
        this.result = result;
    }
}